name: Deploy to development on merge dev branch
'on':
  push:
    branches:
  # add all stage branches
      - dev
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'dev'
      API_GATEWAY_ID: '${{ secrets.DEV_API_GATEWAY_ID }}'
      API_GATEWAY_RESOURCE_ID: '${{ secrets.DEV_API_GATEWAY_RESOURCE_ID }}'
      BASIC_AUTH_USERNAME: '${{ secrets.DEV_BASIC_AUTH_USERNAME }}'
      BASIC_AUTH_PASSWORD: '${{ secrets.DEV_BASIC_AUTH_PASSWORD }}'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Creating env file
      run: | 
        cat > .env << EOF
        API_GATEWAY_ID='${{ env.API_GATEWAY_ID }}'
        API_GATEWAY_RESOURCE_ID='${{ env.API_GATEWAY_RESOURCE_ID }}'
        ENVIRONMENT='${{ env.ENVIRONMENT }}'
        BASIC_AUTH_USERNAME='${{ env.BASIC_AUTH_USERNAME }}'
        BASIC_AUTH_PASSWORD='${{ env.BASIC_AUTH_PASSWORD }}'
        EOF
    - name: Install Serverless Framework
      run: npm install -g serverless@2.21.0
    - name: Install NPM dependencies
      run: npm install
    - name: Install newman
      run: npm install -g newman
    - name: Run Unit Tests
      run: yarn test
    - name: Run sls-offline
      run: yarn dev &
    - name: printenv
      run: printenv
    - name: Run Integration Tests
      run: newman run ./integrations/ServerlessTemplate.postman_collection.json -e ./integrations/dev.postman_environment.json
    - name: Deploy Lambda functions
      # run: sls config credentials --provider aws --key ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} --secret ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }} && yarn deploy_dev
      uses: serverless/github-action@master
      with:
        args: 'deploy --stage dev  --env development'
      env:
       SERVERLESS_ACCESS_KEY: ${{ secrets.DEV_SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
       AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
